# Generated by Django 6.0.4 on 2026-04-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidataCoordenadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('empresa_anterior', models.CharField(choices=[('FLAG', 'Flag'), ('AVON', 'Avon'), ('NATURA', 'Natura'), ('BOTICARIO', 'O Boticário'), ('JEQUITI', 'Jequiti'), ('OUTRAS', 'Outras')], max_length=50, verbose_name='Empresa Anterior')),
                ('empresa_outra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Outra Empresa')),
                ('media_ganhos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Média de Ganhos')),
                ('quantidade_consultoras', models.PositiveIntegerField(verbose_name='Quantidade de Consultoras')),
                ('documento_rg_cnh', models.FileField(upload_to='documentos/rg_cnh/', verbose_name='RG ou CNH')),
                ('documento_cpf', models.FileField(upload_to='documentos/cpf/', verbose_name='CPF')),
                ('comprovante_endereco', models.FileField(upload_to='documentos/endereco/', verbose_name='Comprovante de Endereço')),
                ('comprovante_ganhos', models.FileField(upload_to='documentos/ganhos/', verbose_name='Comprovante de Ganhos')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('AJUSTE', 'Aguardando Ajuste'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacao_aprovacao', models.TextField(blank=True, null=True, verbose_name='Observação de Aprovação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidata a Coordenadora',
                'verbose_name_plural': 'Candidatas a Coordenadoras',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
