# Generated by Django 6.0.4 on 2026-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenadoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatacoordenadora',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='candidatacoordenadora',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/candidatas/', verbose_name='Foto (Opcional)'),
        ),
        migrations.AlterField(
            model_name='candidatacoordenadora',
            name='empresa_anterior',
            field=models.CharField(choices=[('AVON', 'Avon'), ('NATURA', 'Natura'), ('BOTICARIO', 'O Boticário'), ('JEQUITI', 'Jequiti'), ('OUTRAS', 'Outras')], max_length=50, verbose_name='Empresa Anterior'),
        ),
    ]
