# Generated by Django 6.0.4 on 2026-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenadoras', '0002_candidatacoordenadora_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProtheus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(max_length=10, verbose_name='Campanha')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('setor', models.CharField(max_length=10, verbose_name='Setor')),
                ('revendedora', models.CharField(max_length=50, verbose_name='Cód. Revendedora')),
                ('emissao', models.CharField(max_length=10, verbose_name='Data Emissão')),
                ('pedido', models.CharField(max_length=50, verbose_name='Nº Pedido')),
                ('produto', models.CharField(max_length=50, verbose_name='Cód. Produto')),
                ('quantidade', models.FloatField(default=0, verbose_name='Quantidade')),
                ('valor_financeiro', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Financeiro')),
                ('coordenadora', models.CharField(max_length=50, verbose_name='Cód. Coordenadora')),
                ('status_item', models.CharField(max_length=10, verbose_name='Status')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido Protheus',
                'verbose_name_plural': 'Pedidos Protheus',
                'ordering': ['-emissao', '-pedido'],
                'unique_together': {('pedido', 'produto')},
            },
        ),
    ]
