# Generated by Django 6.0.4 on 2026-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenadoras', '0003_pedidoprotheus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoprotheus',
            name='tes',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TES'),
        ),
        migrations.AddField(
            model_name='pedidoprotheus',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
