# Generated by Django 6.0.4 on 2026-04-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenadoras', '0004_pedidoprotheus_tes_pedidoprotheus_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatacoordenadora',
            name='cod_protheus',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Protheus'),
        ),
    ]
