# Generated by Django 6.0.4 on 2026-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenadoras', '0005_candidatacoordenadora_cod_protheus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoprotheus',
            name='campanha',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Campanha'),
        ),
        migrations.AlterField(
            model_name='pedidoprotheus',
            name='coordenadora',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Cód. Coordenadora'),
        ),
    ]
